### ISSUE TITLE
Dont Understand how to run - Im dumb help plz

### ISSUE THREAD

**Issue by oybekx3d** [melvinchia3636/vanillaTweaks#2]
Good day sir, I found your project today and was looking for this for ages. This is the best thing i have ever seen. But the problem is that I am dumb enough to not understand how to host it in my local machine for preview and customizations in windows [10] OS. If you got time can you help/make a tutorial so everyone can use it easily. Thanks a lot! Love this project!

I somehow found the main page but still couldnt use it, it was empty lol.

![image](https://user-images.githubusercontent.com/101323670/231188793-82c81d4a-4a1a-4d53-8489-da2e2218da5a.png)

**Comment by melvinchia3636** [comment]
To run this, you have to install NodeJS on your machine. https://nodejs.org/en

After that, you can follow the instructions written on README.md.

**Comment by oybekx3d** [comment]
> To run this, you have to install NodeJS on your machine. https://nodejs.org/en
> 
> After that, you can follow the instructions written on README.md.

Well I am so sorry but i still dont get it.
I installed NodeJS but what are the dependencies 
and how do i run 'npm install' 
and 'npm run dev'

Also can i use it to host my own website, it is copyright free right?

also idk if this is bug from your side but check out the imgs, i can see some kind of sliders in several places. they are just examples.
![image](https://user-images.githubusercontent.com/101323670/231393663-82bf69a8-d98c-43a8-a88b-d6977e31bd13.png)
![image](https://user-images.githubusercontent.com/101323670/231393683-382a7755-7a97-4726-ba83-af7d0d4733be.png)

**Comment by melvinchia3636** [comment]
Regarding the slider issue, since I was developing this website in MacOS with decent looking scrollbar, I'd never worried about the scrollbar issue. Nevertheless, I'll use some packages to make the scrollbar look better in other OS.

For the copyright, yes, this website is licensed under the MIT License, which gives you full access to downloading, modifying, and distributing the website.

If you're new to NodeJS, there are several good tutorials online, feel free to look them up.
